### ISSUE TITLE
`play()` doesn't work with latest deno `1.26.2` on Windows

### ISSUE THREAD

**Issue by cyantree** [littledivy/deno_audio#8]
I tried to use your module with the latest deno version and stumbled upon the following error:
```
error: Uncaught (in promise) TypeError: Invalid FFI pointer type, expected null, integer or BigInt
await play("music.mp3");
```

This seems to be related to some type changes.
I could fix it by changing `pointer` to `buffer` here:
https://github.com/littledivy/deno_audio/blob/ba12323ed94ef064096597f5774a640ff25329d5/bindings/bindings.ts#L29

**Comment by Keithcat1** [comment]
I got something similar:
```
Uncaught TypeError: Invalid FFI pointer type, expected null, or External
    at Object.value [as play] (ext:deno_ffi/00_ffi.js:526:24)
    at play (https://deno.land/x/audio@0.2.0/bindings/bindings.ts:34:32)
    at <anonymous>:1:36
```
